services:
  db:
    container_name: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ./srcs/secrets/.env.db
    ports:
      - 3306:3306
    volumes:
      - tmp:/var/lib/mysql

volumes:
  tmp:
